server:
  port: 8000

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://61.109.236.137:8761/eureka

auth:
  jwt:
    key: ENC(Q5XM9A3CUXt8XO1VOtQoZRE37aOA/ulmZfgQTM+hG/LIfgVvUeB5VUTOJ4CpLTv1)
