server:
  port: 8000

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    kubernetes:
      discovery:
        enabled: false

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://61.109.236.137:8761/eureka

auth:
  jwt:
    key: ENC(Q5XM9A3CUXt8XO1VOtQoZRE37aOA/ulmZfgQTM+hG/LIfgVvUeB5VUTOJ4CpLTv1)

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /api-docs/users/v3/api-docs
      - name: Post Service
        url: /api-docs/posts/v3/api-docs
      - name: Issue Service
        url: /api-docs/issues/v3/api-docs
      - name: Activity Service
        url: /api-docs/activities/v3/api-docs
