server:
  port: 8000

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    kubernetes:
      discovery:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka

auth:
  jwt:
    key: ${JWT_SECRET}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /api-docs/users/v3/api-docs
      - name: Post Service
        url: /api-docs/posts/v3/api-docs
      - name: Issue Service
        url: /api-docs/issues/v3/api-docs
      - name: Activity Service
        url: /api-docs/activities/v3/api-docs
